-- SYNOPSIS: Database migration — 202311_capsule_id_format.sql.
-- Ensure capsule_id defaults to a UUID v4-style value generated by PostgreSQL
-- Assumes pgcrypto is available or can be enabled for gen_random_uuid()

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE memory_capsules
  ALTER COLUMN capsule_id SET DEFAULT gen_random_uuid();

-- Backfill any NULL capsule_id values using DB-generated UUIDs
UPDATE memory_capsules
SET capsule_id = gen_random_uuid()
WHERE capsule_id IS NULL;

-- Ensure capsule_id is not null going forward
ALTER TABLE memory_capsules
  ALTER COLUMN capsule_id SET NOT NULL;