-- SYNOPSIS: Database migration — 20231012_create_ci_guard.sql.
CREATE TABLE IF NOT EXISTS ci_guard (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);