-- SYNOPSIS: Database migration — 20260717_lifeos_core_phase_3.sql.
CREATE TABLE IF NOT EXISTS phase_3_table (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_phase_3_table_name ON phase_3_table (name);

ALTER TABLE IF EXISTS phase_3_table ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'active';
ALTER TABLE IF EXISTS phase_3_table ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 0;