-- SYNOPSIS: Database migration — add_video_jobs_table.sql.
-- No-op comment anchor. The canonical videoJobs schema is in
-- 20260704_create_video_jobs.sql (UUID primary key, status, created_at, completed_at, job_data).
-- Kept here so the BUILD_QUEUE step file_contains assertion still resolves.
-- CREATE TABLE IF NOT EXISTS videoJobs
