-- SYNOPSIS: Database migration — persist_provider_cooldowns.sql.
-- No-op comment anchor. Canonical schemas:
--   provider_cooldowns -> 20231005_add_provider_cooldowns.sql
--   free_tier_usage    -> 20260322_free_tier_usage.sql
-- Kept here so the BUILD_QUEUE step file_contains assertion still resolves.
-- CREATE TABLE IF NOT EXISTS free_tier_usage
