stages:
  - build_and_test # referencing the Jenkinsfile deployment stage 'Build' and test stages defined in there...
# Additional pipeline configuration for GitLab CI, including Rails integration if necessary...