const express = require('express');
const router = new express.Router();
// ... complete file content with necessary endpoints, handlers...
router.get('/overlays', async function(req, res) {
    // Logic to retrieve available overlays from the database using Neon PostgreSQL driver or ORM (e.g., Sequelize)...
});
// ... more route definitions and error handling as needed...