```sql
CREATE TABLE IF NOT EXISTS funnel_models (
    id SERIAL PRIMARY KEY,
    funnel_id VARCHAR(255) NOT NULL,
    model_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS model_training_jobs (
    id SERIAL PRIMARY KEY,
    funnel_id VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
```