CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password CHAR(60) NOT NULL, -- assuming bcrypt for passwords
  created_at TIMESTAMP WITHO0DING CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);