apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-enhanced-customer-support-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-enhanced-customer-support-system
---
apiVersion: autoscaler/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-ai-enhanced-customer-support-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-enhanced-customer-support-system
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80