-- ╔══════════════════════════════════════════════════════════════════════════════════╗
-- ║                        TCO (TotalCostOptimizer) TABLES                            ║
-- ║              Database schema for the cost savings proxy service                   ║
-- ╚══════════════════════════════════════════════════════════════════════════════════╝

-- TCO Customers table
-- Stores customer accounts who use the TCO service
CREATE TABLE IF NOT EXISTS tco_customers (
  id SERIAL PRIMARY KEY,
  company_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  api_key VARCHAR(255) NOT NULL UNIQUE, -- Their TCO API key (generated by us)
  encrypted_openai_key TEXT, -- Their OpenAI API key (encrypted)
  encrypted_anthropic_key TEXT, -- Their Anthropic API key (encrypted)
  encrypted_google_key TEXT, -- Their Google API key (encrypted)
  monthly_ai_spend_estimate DECIMAL(10, 2) DEFAULT 0, -- Their estimated monthly spend
  status VARCHAR(50) DEFAULT 'active', -- active, paused, cancelled
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Index for fast API key lookups
CREATE INDEX IF NOT EXISTS idx_tco_customers_api_key ON tco_customers(api_key);
CREATE INDEX IF NOT EXISTS idx_tco_customers_email ON tco_customers(email);

-- TCO Requests table (TCO-E01: Savings Ledger)
-- Tracks every proxied request with before/after metrics
CREATE TABLE IF NOT EXISTS tco_requests (
  id BIGSERIAL PRIMARY KEY,
  customer_id INTEGER REFERENCES tco_customers(id) ON DELETE CASCADE,
  customer_api_key VARCHAR(255) NOT NULL, -- For fast lookups without join

  -- What they would have called
  original_provider VARCHAR(50) NOT NULL, -- 'openai', 'anthropic', 'google'
  original_model VARCHAR(100) NOT NULL, -- 'gpt-4', 'claude-3-opus', etc

  -- What we actually called
  actual_provider VARCHAR(50) NOT NULL,
  actual_model VARCHAR(100) NOT NULL,

  -- Token metrics
  original_tokens INTEGER DEFAULT 0, -- Estimated tokens without optimization
  actual_tokens INTEGER DEFAULT 0, -- Actual tokens after compression

  -- Cost metrics (THE PROOF)
  original_cost DECIMAL(10, 6) DEFAULT 0, -- What they would have paid
  actual_cost DECIMAL(10, 6) DEFAULT 0, -- What we paid
  savings DECIMAL(10, 6) DEFAULT 0, -- original_cost - actual_cost
  savings_percent DECIMAL(5, 2) DEFAULT 0, -- (savings / original_cost) * 100

  -- Optimization flags
  cache_hit BOOLEAN DEFAULT FALSE, -- Was this cached?
  compression_used BOOLEAN DEFAULT FALSE, -- Did we use MICRO compression?

  -- Quality metrics
  quality_score INTEGER, -- 0-100 quality score (optional)
  latency_ms INTEGER, -- Response time in milliseconds

  -- Metadata (JSON for flexibility)
  request_metadata JSONB, -- { prompt_tokens, completion_tokens, etc }

  created_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_tco_requests_customer_id ON tco_requests(customer_id);
CREATE INDEX IF NOT EXISTS idx_tco_requests_customer_api_key ON tco_requests(customer_api_key);
CREATE INDEX IF NOT EXISTS idx_tco_requests_created_at ON tco_requests(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tco_requests_customer_date ON tco_requests(customer_id, created_at DESC);

-- TCO Savings Summary (materialized view for fast dashboard queries)
CREATE TABLE IF NOT EXISTS tco_savings_summary (
  id SERIAL PRIMARY KEY,
  customer_id INTEGER REFERENCES tco_customers(id) ON DELETE CASCADE,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,

  total_requests INTEGER DEFAULT 0,
  total_savings DECIMAL(10, 2) DEFAULT 0,
  our_revenue DECIMAL(10, 2) DEFAULT 0, -- 20% of savings

  cache_hit_rate DECIMAL(5, 2) DEFAULT 0, -- Percentage
  avg_savings_percent DECIMAL(5, 2) DEFAULT 0,

  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),

  UNIQUE(customer_id, period_start, period_end)
);

CREATE INDEX IF NOT EXISTS idx_tco_savings_customer ON tco_savings_summary(customer_id);
CREATE INDEX IF NOT EXISTS idx_tco_savings_period ON tco_savings_summary(period_start, period_end);

-- TCO Invoices table
-- Monthly invoices for customers (20% of verified savings)
CREATE TABLE IF NOT EXISTS tco_invoices (
  id SERIAL PRIMARY KEY,
  customer_id INTEGER REFERENCES tco_customers(id) ON DELETE CASCADE,

  invoice_month INTEGER NOT NULL, -- 1-12
  invoice_year INTEGER NOT NULL,

  total_requests INTEGER DEFAULT 0,
  total_savings DECIMAL(10, 2) DEFAULT 0, -- What we saved them
  amount_due DECIMAL(10, 2) DEFAULT 0, -- 20% of savings

  status VARCHAR(50) DEFAULT 'pending', -- pending, paid, overdue, cancelled
  stripe_invoice_id VARCHAR(255), -- Stripe invoice ID
  paid_at TIMESTAMP,

  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),

  UNIQUE(customer_id, invoice_year, invoice_month)
);

CREATE INDEX IF NOT EXISTS idx_tco_invoices_customer ON tco_invoices(customer_id);
CREATE INDEX IF NOT EXISTS idx_tco_invoices_status ON tco_invoices(status);
CREATE INDEX IF NOT EXISTS idx_tco_invoices_period ON tco_invoices(invoice_year, invoice_month);

-- Function to update customer updated_at timestamp
CREATE OR REPLACE FUNCTION update_tco_customer_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update timestamp
CREATE TRIGGER tco_customer_updated
  BEFORE UPDATE ON tco_customers
  FOR EACH ROW
  EXECUTE FUNCTION update_tco_customer_timestamp();

-- Grant permissions (adjust as needed for your setup)
-- GRANT SELECT, INSERT, UPDATE ON tco_customers, tco_requests, tco_savings_summary, tco_invoices TO your_app_user;
-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO your_app_user;

-- Success message
DO $$
BEGIN
  RAISE NOTICE 'TCO tables created successfully!';
  RAISE NOTICE 'Tables: tco_customers, tco_requests, tco_savings_summary, tco_invoices';
  RAISE NOTICE 'Ready to track cost savings and generate revenue!';
END $$;
