export const COUNCIL_ALIAS_MAP = {
  claude: "claude_sonnet",
  anthropic: "claude_sonnet",
  chatgpt: "groq_llama",
  openai: "groq_llama",
  gemini: "gemini_flash",
  grok: "groq_llama",
  deepseek: "deepseek",
};

export function createCouncilMembers({ OLLAMA_ENDPOINT, DEEPSEEK_BRIDGE_ENABLED }) {
  const ollamaEndpoint = OLLAMA_ENDPOINT || "http://localhost:11434";

  return {
    // ── Anthropic Claude (paid, high-quality codegen) ──────────────────────
    claude_sonnet: {
      name: "Claude Sonnet 4.6 (Anthropic)",
      model: process.env.ANTHROPIC_MODEL || "claude-sonnet-4-6",
      provider: "anthropic",
      role: "Primary Code Author & Builder",
      focus: "production code generation, complex reasoning, ESM Node.js, long-form output",
      maxTokens: 16000,
      tier: "tier1",
      costPer1M: 3.0,   // $3/M input, $15/M output (Sonnet pricing)
      specialties: ["code", "code_generation", "reasoning", "production", "esm", "architecture"],
      isFree: false,
      isLocal: false,
      priority: "highest",
    },

    ollama_deepseek: {
      name: "DeepSeek Coder (Local)",
      model: "deepseek-coder:latest",
      provider: "ollama",
      endpoint: ollamaEndpoint,
      role: "Primary Developer & Infrastructure",
      focus: "optimization, performance, safe testing, development, code generation",
      maxTokens: 4096,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["infrastructure", "testing", "performance", "development", "code"],
      isFree: true,
      isLocal: true,
    },
    ollama_llama: {
      name: "Llama 3.2 (Local)",
      model: "llama3.2:1b",
      provider: "ollama",
      endpoint: ollamaEndpoint,
      role: "General Assistant & Research",
      focus: "general tasks, research, analysis, reasoning",
      maxTokens: 8192,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["research", "analysis", "general"],
      isFree: true,
      isLocal: true,
    },
    deepseek: {
      name: "DeepSeek Cloud",
      model: "deepseek-coder",
      provider: "deepseek",
      role: "Primary Developer & Infrastructure (Cloud Fallback)",
      focus: "optimization, performance, safe testing, development",
      maxTokens: 4096,
      tier: "tier0",
      costPer1M: 0.1,
      specialties: ["infrastructure", "testing", "performance", "development"],
      useLocal: DEEPSEEK_BRIDGE_ENABLED === "true",
      isFree: false,
    },
    groq_llama: {
      name: "Groq Llama (Free)",
      model: process.env.GROQ_MODEL || "llama-3.1-8b-instant",
      provider: "groq",
      role: "Fast Cloud Generalist",
      focus: "quick routing, lightweight reasoning, free-tier responses",
      maxTokens: 4096,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["fast", "routing", "general", "reasoning"],
      isFree: true,
      isLocal: false,
    },
    gemini_flash: {
      name: "Gemini Flash (Free)",
      model: process.env.GEMINI_MODEL || "gemini-2.5-flash",
      provider: "gemini",
      role: "Fast Cloud Reasoning",
      focus: "summaries, planning, lightweight analysis, free-tier responses",
      maxTokens: 8192,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["analysis", "planning", "summaries", "reasoning"],
      isFree: true,
      isLocal: false,
    },
    cerebras_llama: {
      name: "Cerebras Llama (Free)",
      model: process.env.CEREBRAS_MODEL || "llama3.1-8b",
      provider: "cerebras",
      role: "High-Speed Cloud Reasoning",
      focus: "fast generation, routing, throughput-heavy tasks",
      maxTokens: 8192,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["speed", "throughput", "reasoning", "general"],
      isFree: true,
      isLocal: false,
    },
    openrouter_free: {
      name: "OpenRouter Free",
      model: process.env.OPENROUTER_MODEL || "meta-llama/llama-3.1-8b-instruct:free",
      provider: "openrouter",
      role: "Free Model Aggregator",
      focus: "fallback routing across free hosted models",
      maxTokens: 4096,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["fallback", "general", "routing"],
      isFree: true,
      isLocal: false,
    },
    mistral_free: {
      name: "Mistral Free",
      model: process.env.MISTRAL_MODEL || "open-mistral-7b",
      provider: "mistral",
      role: "Lightweight Cloud Assistant",
      focus: "concise generation, chat, lightweight planning",
      maxTokens: 4096,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["chat", "planning", "lightweight"],
      isFree: true,
      isLocal: false,
    },
    together_free: {
      name: "Together Free",
      model: process.env.TOGETHER_MODEL || "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
      provider: "together",
      role: "Shared Cloud Fallback",
      focus: "free/shared routing, fallback execution, fast responses",
      maxTokens: 4096,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["fallback", "speed", "general"],
      isFree: true,
      isLocal: false,
    },
    ollama_deepseek_coder_v2: {
      name: "DeepSeek Coder V2 (Local)",
      model: "deepseek-coder-v2:latest",
      provider: "ollama",
      endpoint: ollamaEndpoint,
      role: "Code Generation Specialist",
      focus: "code generation, code review, debugging, infrastructure, production code",
      maxTokens: 8192,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["code", "code_review", "debugging", "infrastructure", "development"],
      isFree: true,
      isLocal: true,
      priority: "high",
    },
    ollama_deepseek_coder_33b: {
      name: "DeepSeek Coder 33B (Local)",
      model: "deepseek-coder:33b",
      provider: "ollama",
      endpoint: ollamaEndpoint,
      role: "Code Generation Specialist (Large)",
      focus: "complex code generation, advanced algorithms, production code",
      maxTokens: 8192,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["code", "complex_algorithms", "production_code"],
      isFree: true,
      isLocal: true,
    },
    ollama_qwen_coder_32b: {
      name: "Qwen2.5-Coder-32B (Local)",
      model: "qwen2.5-coder:32b-instruct",
      provider: "ollama",
      endpoint: ollamaEndpoint,
      role: "Code Generation Specialist",
      focus: "production code generation, complex algorithms, code understanding",
      maxTokens: 8192,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["code", "code_generation", "algorithms", "production"],
      isFree: true,
      isLocal: true,
    },
    ollama_codestral: {
      name: "Mistral Codestral 25.01 (Local)",
      model: "codestral:latest",
      provider: "ollama",
      endpoint: ollamaEndpoint,
      role: "Fast Code Generation",
      focus: "quick code snippets, IDE integration, FIM tasks, fast responses",
      maxTokens: 4096,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["code", "fast_code", "snippets", "fim"],
      isFree: true,
      isLocal: true,
    },
    ollama_deepseek_v3: {
      name: "DeepSeek V3 (Local)",
      model: "deepseek-v3:latest",
      provider: "ollama",
      endpoint: ollamaEndpoint,
      role: "Complex Reasoning Specialist",
      focus: "complex reasoning, mathematical tasks, strategic decisions, exceptional reasoning",
      maxTokens: 128000,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["reasoning", "math", "strategic_decisions", "complex_analysis"],
      isFree: true,
      isLocal: true,
      priority: "high",
    },
    ollama_llama_3_3_70b: {
      name: "Llama 3.3 70B (Local)",
      model: "llama3.3:70b-instruct-q4_0",
      provider: "ollama",
      endpoint: ollamaEndpoint,
      role: "High-Quality Reasoning",
      focus: "complex reasoning, strategic decisions, general tasks, multilingual",
      maxTokens: 8192,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["reasoning", "strategic_decisions", "general", "multilingual"],
      isFree: true,
      isLocal: true,
    },
    ollama_qwen_2_5_72b: {
      name: "Qwen 2.5 72B (Local)",
      model: "qwen2.5:72b-q4_0",
      provider: "ollama",
      endpoint: ollamaEndpoint,
      role: "Research & Analysis Specialist",
      focus: "research, analysis, mathematical tasks, multilingual, document understanding",
      maxTokens: 8192,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["research", "analysis", "math", "multilingual", "documents"],
      isFree: true,
      isLocal: true,
    },
    ollama_gemma_2_27b: {
      name: "Gemma 2 27B (Local)",
      model: "gemma2:27b-it-q4_0",
      provider: "ollama",
      endpoint: ollamaEndpoint,
      role: "Balanced Reasoning",
      focus: "on-device reasoning, balanced performance, general tasks",
      maxTokens: 8192,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["reasoning", "general", "balanced"],
      isFree: true,
      isLocal: true,
    },
    ollama_phi3: {
      name: "Phi-3 Mini (Local)",
      model: "phi3:mini",
      provider: "ollama",
      endpoint: ollamaEndpoint,
      role: "Lightweight Assistant",
      focus: "light tasks, monitoring, simple analysis, fast responses",
      maxTokens: 4096,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["light_tasks", "monitoring", "simple_analysis"],
      isFree: true,
      isLocal: true,
    },
  };
}
