/**
 * SYNOPSIS: Exports createCouncilMembers — config/council-members.js.
 *
 * @ssot docs/products/ai-council/PRODUCT_HOME.md
 */
export const COUNCIL_ALIAS_MAP = {
  claude: "claude_sonnet",    // direct Anthropic only — OpenRouter retired (Adam 2026-05-24)
  anthropic: "claude_sonnet",
  chatgpt: "openai_gpt",
  openai: "openai_gpt",
  groq: "groq_llama",
  gemini: "gemini_flash",
  grok: "groq_llama",
  deepseek: "deepseek",
  century: "century",
  // Founder directive (2026-06-30): hard-retire Ollama names to cloud/runtime-safe lanes.
  ollama_deepseek: "deepseek",
  ollama_llama: "groq_llama",
  ollama_phi: "mistral_free",
  ollama_phi3: "mistral_free",
  ollama_deepseek_coder_v2: "openai_builder_mini",
  ollama_deepseek_coder_33b: "openai_builder_standard",
  ollama_qwen_coder_32b: "openai_builder_standard",
  ollama_codestral: "openai_builder_mini",
  ollama_deepseek_v3: "deepseek",
  ollama_llama_3_3_70b: "cerebras_llama",
  ollama_qwen_2_5_72b: "gemini_flash",
  ollama_gemma_2_27b: "mistral_free",
};

export function createCouncilMembers({ DEEPSEEK_BRIDGE_ENABLED }) {
  return {
    claude_sonnet: {
      name: "Claude Sonnet 4.6 (Anthropic direct)",
      model: process.env.ANTHROPIC_MODEL || "claude-sonnet-4-6",
      provider: "anthropic",
      role: "Primary Code Author & Builder",
      focus: "production code generation, complex reasoning, ESM Node.js, long-form output",
      maxTokens: 16000,
      tier: "tier1",
      costPer1M: 3.0,
      specialties: ["code", "code_generation", "reasoning", "production", "esm", "architecture"],
      isFree: false,
      isLocal: false,
      priority: "highest",
    },
    openai_gpt: {
      name: "OpenAI GPT",
      model: process.env.OPENAI_MODEL || process.env.OPENAI_CHAT_MODEL || "gpt-4o",
      provider: "openai",
      role: "OpenAI Direct",
      focus: "general conversation, reasoning, Voice Rail when operator picks OpenAI",
      maxTokens: 8192,
      tier: "tier1",
      costPer1M: 2.5,
      specialties: ["conversation", "reasoning", "general", "analysis"],
      isFree: false,
      isLocal: false,
      priority: "high",
    },
    openai_builder_mini: {
      name: "OpenAI Builder Mini",
      model: process.env.BUILDEROS_MODEL_DEFAULT || process.env.OPENAI_MODEL || "gpt-4o-mini",
      provider: "openai",
      role: "Cheapest-capable BuilderOS executor",
      focus: "frozen blueprint execution, bounded code edits, low-cost repair attempts",
      maxTokens: 8192,
      tier: "tier0",
      costPer1M: 0.5,
      specialties: ["code", "bounded_patching", "execution", "repair", "builderos"],
      isFree: false,
      isLocal: false,
      priority: "high",
    },
    openai_builder_standard: {
      name: "OpenAI Builder Standard",
      model: process.env.BUILDEROS_MODEL_STANDARD || process.env.OPENAI_CHAT_MODEL || "gpt-4o",
      provider: "openai",
      role: "BuilderOS standard reasoning lane",
      focus: "planning, reviews, harder multi-file bounded repairs, governance-safe coding",
      maxTokens: 16384,
      tier: "tier1",
      costPer1M: 2.5,
      specialties: ["code", "planning", "review", "reasoning", "builderos"],
      isFree: false,
      isLocal: false,
      priority: "high",
    },
    openai_builder_escalation: {
      name: "OpenAI Builder Escalation",
      model: process.env.BUILDEROS_MODEL_ESCALATION || "gpt-4o",
      provider: "openai",
      role: "BuilderOS escalation lane",
      focus: "high-risk repairs, conflict resolution, harder blueprint implementation edge cases",
      maxTokens: 16384,
      tier: "tier1",
      costPer1M: 5.0,
      specialties: ["code", "escalation", "reasoning", "governance", "builderos"],
      isFree: false,
      isLocal: false,
      priority: "highest",
    },
    century: {
      name: "Century (long-horizon strategy)",
      model: process.env.CENTURY_MODEL || "o1",
      provider: "openai",
      role: "Long-horizon strategy and architect-level reasoning",
      focus: "high-level planning, conflict resolution, multi-week blueprint sequencing",
      maxTokens: 16384,
      tier: "tier1",
      costPer1M: 5.0,
      specialties: ["reasoning", "architecture", "strategy", "governance", "planning"],
      isFree: false,
      isLocal: false,
      priority: "highest",
    },
    deepseek: {
      name: "DeepSeek Cloud",
      model: process.env.DEEPSEEK_MODEL || "deepseek-chat",
      provider: "deepseek",
      role: "Primary Developer & Infrastructure (Cloud Fallback)",
      focus: "optimization, performance, safe testing, development",
      maxTokens: 4096,
      tier: "tier0",
      costPer1M: 0.1,
      specialties: ["infrastructure", "testing", "performance", "development"],
      useLocal: DEEPSEEK_BRIDGE_ENABLED === "true",
      isFree: false,
    },
    groq_llama: {
      name: "Groq Llama (Free)",
      model: process.env.GROQ_MODEL || "llama-3.1-8b-instant",
      provider: "groq",
      role: "Fast Cloud Generalist",
      focus: "quick routing, lightweight reasoning, free-tier responses",
      maxTokens: 4096,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["fast", "routing", "general", "reasoning"],
      isFree: true,
      isLocal: false,
    },
    gemini_flash: {
      name: "Gemini Flash (Free)",
      model: process.env.GEMINI_MODEL || "gemini-2.5-flash",
      provider: "gemini",
      role: "Fast Cloud Reasoning",
      focus: "summaries, planning, lightweight analysis, free-tier responses",
      maxTokens: 8192,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["analysis", "planning", "summaries", "reasoning"],
      isFree: true,
      isLocal: false,
    },
    cerebras_llama: {
      name: "Cerebras Llama (Free)",
      model: process.env.CEREBRAS_MODEL || "llama3.1-8b",
      provider: "cerebras",
      role: "High-Speed Cloud Reasoning",
      focus: "fast generation, routing, throughput-heavy tasks",
      maxTokens: 8192,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["speed", "throughput", "reasoning", "general"],
      isFree: true,
      isLocal: false,
    },
    mistral_free: {
      name: "Mistral Free",
      model: process.env.MISTRAL_MODEL || "open-mistral-7b",
      provider: "mistral",
      role: "Lightweight Cloud Assistant",
      focus: "concise generation, chat, lightweight planning",
      maxTokens: 4096,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["chat", "planning", "lightweight"],
      isFree: true,
      isLocal: false,
    },
    github_llama: {
      name: "GitHub Models DeepSeek V3 (Free)",
      model: process.env.GITHUB_MODELS_MODEL || "DeepSeek-V3-0324",
      provider: "github_models",
      role: "High-Quality Free Cloud Coding & Reasoning",
      focus: "code generation, complex reasoning, analysis — uses GITHUB_TOKEN quota; backup to direct DeepSeek API",
      maxTokens: 8192,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["reasoning", "code_review", "analysis", "general"],
      isFree: true,
      isLocal: false,
    },
    fireworks_llama: {
      name: "Fireworks Llama 3.1 8B (Credit)",
      model: process.env.FIREWORKS_MODEL || "accounts/fireworks/models/llama-v3p1-8b-instruct",
      provider: "fireworks",
      role: "Free Credit Cloud Fallback",
      focus: "fast generation, general tasks — uses $1 free credit",
      maxTokens: 4096,
      tier: "tier0",
      costPer1M: 0,
      specialties: ["fast", "general", "fallback"],
      isFree: true,
      isLocal: false,
    },
  };
}
