CREATE TABLE IF NOT EXISTS scenarios (
    ScenarioID SERIAL PRIMARY KEY,
    Title VARCHAR(255),
    Description TEXT,
    Requirements JSONB,
    Status VARCHAR(50) DEFAULT 'Pending',
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT0TIM3124987.6+-01:00