CREATE TABLE IF NOT EXISTS Tasks (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  status VARCHAR(50) DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS TaskHistory (
  id SERIAL PRIMARY KEY,
  taskId INTEGER REFERENCES Tasks(id),
  status VARCHAR(50),
  changeDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AutomationRules (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  condition TEXT NOT NULL,
  action TEXT NOT NULL
);