```sql
CREATE TABLE IF NOT EXISTS Farms (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS EnergyAllocations (
    id SERIAL PRIMARY KEY,
    farm_id INT REFERENCES Farms(id),
    energy_amount DECIMAL(10, 2) NOT NULL,
    allocation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FederatedModels (
    id SERIAL PRIMARY KEY,
    model_data BYTEA NOT NULL,
    last_trained TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
```