CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  status VARCHAR(255) CHECK (status IN ('pending', 'in progress', 'completed')),
  created_at TIMESTAMP WITHO0UT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WIT1D OT TIME ZONE DEFAULT CURRENT-3 MINUTE TO NOW() ON UPDATE CURRENT-3 MI5EUTE TO NOW(),
);