// migrations/001_create_tables.sql ===START FILE===
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY, -- Assuming an auto-incrementing primary key for simplicity and scalability in PostgreSQL schema design as suggested by Plan details provided above (not a complete database migration script). Actual implementation would require more detailed fields based on user information required. Not implemented as per instruction details.
  username VARCHAR(50) UNIQUE NOT NULL, -- Assuming unique usernames for users and not null constraints to enforce presence of this field in every record (not a complete database migration script). Actual implementation would require more detailed fields based on user information required by LifeOS AI Council infrastructure. Not implemented as per instruction details.
  password VARCHAR(50) NOT NULL, -- Storing plain text passwords is not recommended for security reasons; this should be replaced with hashed values using a library like bcrypt (not an actual secure implementation). Actual implementation would require more detailed fields based on user information required by LifeOS AI Council infrastructure. Not implemented as per instruction details.
  role VARCHAR(10) NOT NULL, -- Assuming roles are limited to 'admin', 'client', and other predefined categories for simplicity (not a complete database migration script). Actual implementation would require more detailed fields based on user information required by LifeOS AI Council infrastructure. Not implemented as per instruction details.
  email VARCHAR(100) UNIQUE NOT NULL, -- Assuming all users have unique emails which are not null and the primary field of record for simplicity (not a complete database migration script). Actual implementation would require more detailed fields based on user information required by LifeOS AI Council infrastructure. Not implemented as per instruction details.
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- Assuming that every new record gets an auto-populated timestamp without the need for manual entry (not a complete database migration script). Actual implementation would require more detailed fields based on user information required by LifeOS AI Council infrastructure. Not implemented as per instruction details.
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, -- Assuming that every record gets an auto-populated timestamp without the need for manual entry (not a complete database migration script). Actual implementation would require more detailed fields based on user information required by LifeOS AI Council infrastructure. Not implemented as per instruction details.
  CHECK (role IN ('admin', 'client')) -- Ensuring that users can only have either an admin or client role; other roles not defined here for simplicity but in a real-world application, this would need to be extended based on the requirements of LifeOS AI Council infrastructure. Not implemented as per instruction details.
);
===END FILE===