name: Autopilot Build (Scheduled + Manual)

on:
  schedule:
    - cron: "0 * * * *"   # hourly
  workflow_dispatch:
    inputs:
      app_url:
        description: "Public base URL (e.g., https://robust-magic-production.up.railway.app)"
        required: false
      key:
        description: "COMMAND_CENTER_KEY (optional; uses secret if blank)"
        required: false

concurrency:
  group: autopilot-build
  cancel-in-progress: false

jobs:
  build_now:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Resolve inputs
        id: cfg
        run: |
          APP_URL="${{ github.event.inputs.app_url }}"
          if [ -z "$APP_URL" ]; then APP_URL="${{ secrets.APP_URL }}"; fi
          if [ -z "$APP_URL" ]; then
            echo "APP_URL is required (provide input or set secrets.APP_URL)."
            exit 1
          fi
          KEY_IN="${{ github.event.inputs.key }}"
          if [ -z "$KEY_IN" ]; then KEY_IN="${{ secrets.COMMAND_CENTER_KEY }}"; fi
          if [ -z "$KEY_IN" ]; then
            echo "COMMAND_CENTER_KEY is required (provide input or set secrets.COMMAND_CENTER_KEY)."
            exit 1
          fi
          echo "APP_URL=$APP_URL" >> $GITHUB_OUTPUT
          echo "KEY=$KEY_IN"      >> $GITHUB_OUTPUT

      - name: Heartbeat + build-now (with retries)
        env:
          APP_URL: ${{ steps.cfg.outputs.APP_URL }}
          KEY:     ${{ steps.cfg.outputs.KEY }}
        run: |
          set -e
          echo "Heartbeat..."
          curl --retry 3 --retry-delay 2 --max-time 15 -fsS "$APP_URL/internal/cron/autopilot?key=$KEY" || true

          echo "Trigger build-now..."
          curl --retry 3 --retry-delay 2 --max-time 30 -fsS \
            -X POST "$APP_URL/internal/autopilot/build-now?key=$KEY" \
            -H "Content-Type: application/json" \
            -d '{}' | tee /tmp/resp.json || true

          echo "Daily report tick..."
          curl --retry 3 --retry-delay 2 --max-time 20 -fsS \
            -X POST "$APP_URL/api/v1/autopilot/tick" \
            -H "X-Command-Key: $KEY" \
            -H "Content-Type: application/json" \
            -d '{}' || true

          echo "Overlay status..."
          curl --retry 3 --retry-delay 2 --max-time 10 -fsS "$APP_URL/api/overlay/status" || true

          echo "Done."
