name: Auto Lint

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/*.md"
      - "docs/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show changed files
        id: changed
        run: |
          set -e
          echo "BASE_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
          echo "HEAD_SHA=${{ github.sha }}" >> $GITHUB_OUTPUT
          git fetch --no-tags --prune --depth=2 origin ${{ github.event.pull_request.base.ref }} || true
          echo "Changed files vs base:"
          git diff --name-only "${{ github.event.pull_request.base.sha }}" "${{ github.sha }}" || true

      - name: Basic quality checks (docs only)
        run: |
          set -e
          CHANGED=$(git diff --name-only "${{ github.event.pull_request.base.sha }}" "${{ github.sha }}" | tr -d '\r' | grep -E '\.md$|^docs/' || true)
          if [ -z "$CHANGED" ]; then
            echo "No docs/markdown changes. Skipping."
            exit 0
          fi

          echo "$CHANGED" | while read -r f; do
            [ -f "$f" ] || continue
            if grep -nE "As an AI" "$f"; then
              echo "::error file=$f::Found 'As an AI' phrasing."
              exit 1
            fi
            if echo "$f" | grep -qE '\.md$|^docs/'; then
              if grep -nE "(^|[[:space:]])TODO([[:space:]]|:|$)" "$f"; then
                echo "::error file=$f::Found TODO in docs/markdown; please resolve or move to issues."
                exit 1
              fi
            fi
          done

          echo "Docs/markdown quality checks passed."
