name: Build Cards From Seed

on:
  push:
    paths:
      - "todos/ALL_CARDS.md"
  workflow_dispatch:
    inputs:
      app_url:
        description: "Override APP_URL (defaults to secrets.APP_URL)"
        required: false
      key:
        description: "Override COMMAND_CENTER_KEY (defaults to secrets.COMMAND_CENTER_KEY)"
        required: false

concurrency:
  group: cards-from-seed
  cancel-in-progress: true

jobs:
  build_cards:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Generate plan from seed
        id: plan
        run: |
          node scripts/cards/parse-seed.mjs > /tmp/plan.json
          echo "Plan generated:"
          cat /tmp/plan.json | head -c 4000 || true

      - name: Resolve APP_URL/KEY
        id: cfg
        run: |
          APP_URL="${{ github.event.inputs.app_url }}"
          if [ -z "$APP_URL" ]; then APP_URL="${{ secrets.APP_URL }}"; fi
          if [ -z "$APP_URL" ]; then
            echo "APP_URL is required (set repo secret APP_URL or pass input)."
            exit 1
          fi
          KEY="${{ github.event.inputs.key }}"
          if [ -z "$KEY" ]; then KEY="${{ secrets.COMMAND_CENTER_KEY }}"; fi
          if [ -z "$KEY" ]; then
            echo "COMMAND_CENTER_KEY is required (set repo secret or pass input)."
            exit 1
          fi
          echo "APP_URL=$APP_URL" >> $GITHUB_OUTPUT
          echo "KEY=$KEY" >> $GITHUB_OUTPUT

      - name: Apply plan -> open PR
        env:
          APP_URL: ${{ steps.cfg.outputs.APP_URL }}
          KEY: ${{ steps.cfg.outputs.KEY }}
        run: |
          set -e
          echo "Submitting plan to builder..."
          curl --retry 3 --retry-delay 2 --max-time 60 -fsS \
            -X POST "$APP_URL/api/v1/build/apply-plan?key=$(printf %s "$KEY" | jq -s -R -r @uri)" \
            -H "Content-Type: application/json" \
            --data-binary @/tmp/plan.json \
            | tee /tmp/apply.json
          echo "Done."
