name: Keep System Alive & Working

on:
  schedule:
    # Every 30 seconds is NOT possible in GitHub Actions (minimum is 5 minutes)
    # But we can use multiple schedules to hit it more frequently
    - cron: '*/5 * * * *'    # Every 5 minutes - Health check
    - cron: '2,12,22,32,42,52 * * * *'  # Every 10 minutes offset - Autopilot
    - cron: '0 * * * *'      # Every hour - Generate work
  
  workflow_dispatch:  # Allow manual trigger

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: System Health Check
        run: |
          curl -f https://robust-magic-production.up.railway.app/health || exit 1
          echo "✅ Health check passed"

  autopilot-heartbeat:
    runs-on: ubuntu-latest
    needs: health-check
    steps:
      - name: Autopilot Heartbeat
        run: |
          curl -f "https://robust-magic-production.up.railway.app/internal/cron/autopilot?key=MySecretKey2025LifeOS"
          echo "✅ Autopilot heartbeat sent"

  generate-work:
    runs-on: ubuntu-latest
    needs: autopilot-heartbeat
    steps:
      - name: Generate Work Queue
        run: |
          curl -X POST -f "https://robust-magic-production.up.railway.app/api/v1/autopilot/generate-work?key=MySecretKey2025LifeOS"
          echo "✅ Work queue refreshed"
```

---

## WHAT THIS DOES:

1. **Architect Panel** - Your 24/7 control center, auto-refreshes every 30 seconds
2. **GitHub Actions** - Pings your system every 5-10 minutes (GitHub's limit, can't do 30 seconds)
3. **Work Queue** - Generates tasks continuously, never idle

---

## TO UPLOAD:

1. **architect.html**: GitHub → `public/overlay/` → Upload
2. **keep-alive.yml**: GitHub → Create `.github/workflows/` folder → Upload

Then visit:
```
https://robust-magic-production.up.railway.app/overlay/architect.html?key=MySecretKey2025LifeOS
