name: Keep System Alive

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Health Check
        run: curl -f https://robust-magic-production.up.railway.app/health
      
      - name: Autopilot
        run: curl -f "https://robust-magic-production.up.railway.app/internal/cron/autopilot?key=MySecretKey2025LifeOS"
      
      - name: Generate Work
        run: curl -X POST -f "https://robust-magic-production.up.railway.app/api/v1/autopilot/generate-work?key=MySecretKey2025LifeOS"
