name: Keep System Alive

on:
  schedule:
    - cron: '*/5 * * * *'
    - cron: '*/10 * * * *'
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Health Check
        run: curl -f https://robust-magic-production.up.railway.app/health
      
      - name: Autopilot
        run: curl -f "https://robust-magic-production.up.railway.app/internal/cron/autopilot?key=MySecretKey2025LifeOS"
      
      - name: Generate Work
        run: curl -X POST -f "https://robust-magic-production.up.railway.app/api/v1/autopilot/generate-work?key=MySecretKey2025LifeOS"
```

6. Commit with message: "Fix keep-alive workflow syntax"

---

## 📋 About the Checkboxes

That was just a **checklist for YOU** to track your progress. It's not code - just a list to help you verify everything is working. Ignore it now that you're basically done!

---

## 🎯 FINAL STATUS
```
✅ architect.html - WORKING PERFECTLY
✅ System running - HEALTHY
✅ Work queue - AUTO-GENERATING TASKS
✅ Commands working - REVENUE TASKS CREATED
⚠️ keep-alive.yml - NEEDS SYNTAX FIX (5 minutes)
